[package]
name = "rust-docker-sample"
version = "0.1.0"
authors = ["teketekere <ouie-ahaaaan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
